#!/usr/bin/env bash
# Basic proxy test

set -e

: "${THORDATA_RESIDENTIAL_USERNAME:?Set THORDATA_RESIDENTIAL_USERNAME}"
: "${THORDATA_RESIDENTIAL_PASSWORD:?Set THORDATA_RESIDENTIAL_PASSWORD}"
: "${THORDATA_PROXY_HOST:=pr.thordata.net}"
: "${THORDATA_PROXY_PORT:=9999}"

PROXY_USER="td-customer-${THORDATA_RESIDENTIAL_USERNAME}"
PROXY_URL="http://${PROXY_USER}:${THORDATA_RESIDENTIAL_PASSWORD}@${THORDATA_PROXY_HOST}:${THORDATA_PROXY_PORT}"

echo "🌐 Basic Proxy Test"
echo "   Proxy: ${THORDATA_PROXY_HOST}:${THORDATA_PROXY_PORT}"
echo ""

curl -s -x "$PROXY_URL" "https://httpbin.org/ip" | jq .